default:
	tar -czvf Prog1_WS17-WIRTH-JAN-HA08.tar.gz *.py
dev_fct:
	watch ./nltk_pipeline_main.py fct koko_transcript.txt koko_transcript_processed_fct.txt
dev_cls:
	watch ./nltk_pipeline_main.py cls koko_transcript.txt koko_transcript_processed_cls.txt
